### PR TITLE
Sending initial message to several channels

### PR DESCRIPTION
**Pull request by GeboArt**
In src/bot.py - funtion send_start_prompt

```
#Add to your defined environment variables file (.ENV - .VENV - ETC...) more than 1 Channel ID: DISCORD_CHANNEL_ID="123456, 7891011"    
    #Get DISCORD_CHANNEL_ID values as a list
    discord_channel_ids = os.getenv("DISCORD_CHANNEL_ID").split(",")

    #Iterate over the DISCORD_CHANNEL_ID values and do something with each one
    for discord_channel_id in discord_channel_ids:

        #Do something with the value of discord_channel_id   
        print(f"Trabajando con el canal {discord_channel_id}")
        config_dir = os.path.abspath(f"{__file__}/../../")
        prompt_name = 'starting-prompt.txt'
        prompt_path = os.path.join(config_dir, prompt_name)

        #Get the Discord channel corresponding to the channel ID
        channel = client.get_channel(int(discord_channel_id))
```

### CODE REVIEW

**Comment by Zero6992** [comment]
So the feature is adding the ability to send the starting-prompt to multiple channels? Am I correct?

**Comment by GeboArt** [comment]
Yes @Zero6992. It's correct.

**Comment by Zero6992** [comment]
I left a comment, can you fix it?

**Comment by Zero6992** [comment]
lack of interaction

**Pull request closed without merging**
