### PR TITLE
Formmating fix - check previous first

### PR DESCRIPTION
**Pull request by MohamedAl-Nassirat**
Fixing an issue if the code block is greater than 2000 characters, then it sends the message, and continues the code block in the new message until the message is done

this is an updated solution to the issue #34 that I created https://github.com/Zero6992/chatGPT-discord-bot/issues/34

also fixed an index out of range bug if there is no explanation after the codeblock

here was the issue before: (if the codeblock was greater then 2000 characters, cause an error)
image

and after my fixes: (fixed, now it works if codeblock is > 2000 characters and if message is over 2000 characters as well. Tested on around ~100 different prompts.
image

### CODE REVIEW

**Comment by axsddlr** [comment]
i would suggest rebasing this commit to your previous PR

**Comment by MohamedAl-Nassirat** [comment]
> i would suggest rebasing this commit to your previous PR 

Sure will do

**Comment by Zero6992** [comment]
It looks likes not, could you help me resolve the merge conflicts? I will accept it then

**Comment by Zero6992** [comment]
Many thanks

**Comment by axsddlr** [comment]
rebasing is merging multiple commits into one. Better for workflow and readability. 

@Zero6992 as a suggestion, you assert contributors to  merge their commits before pushing a PR for your codebase sanity

**Comment by Zero6992** [comment]
> rebasing is merging multiple commits into one. Better for workflow and readability.
> 
> @Zero6992 as a suggestion, you assert contributors to merge their commits before pushing a PR for your codebase sanity

I see, thanks for the suggestion

**Pull request merged**
