### PR TITLE
Verify if dependency is updated with requirements.txt

### PR DESCRIPTION
**Pull request by jacky-chay**
Will this be helpful ? 

whenever main.py is executed.
it will run pip install with the appropriate requirements.txt according if environment is a docker environment.

if environment is docker, it will use requirementsDocker.txt
if environment NOT docker, it will use requirements.txt

therefore user will not face any issues anymore if they have missed out to run pip install command again in the future if there's an upgrade of dependency again.

I have not tested the python main.py on docker environment yet since, there seems to be alot of things to do to setup vpn and so~ but it should have work in theory and logic.
tested on windows environment, it works on windows.

### CODE REVIEW

**Comment by Zero6992** [comment]
It seem 0.0.42.1 just released, I will see what I can do

**Comment by aW3ikun** [comment]
I think running a bash script using python is not a good idea. 
I refer to this https://stackoverflow.com/questions/69345839/how-to-run-a-pip-install-command-from-a-subproces-run.
> In general, though, I recommend avoiding reliance on a shell. That is, after all, why you are using Python and not, say, Bash.

**Comment by jacky-chay** [comment]
> I think running a bash script using python is not a good idea. 
> I refer to this https://stackoverflow.com/questions/69345839/how-to-run-a-pip-install-command-from-a-subproces-run.
> > In general, though, I recommend avoiding reliance on a shell. That is, after all, why you are using Python and not, say, Bash.
> 
> Manually installing dependencies is more controllable than it.

Hi,

yup u r right, i agreed that installing dependencies manually is more better. but just realise that many of them are raising issues saying forgotten to run pip install whenever some dependencies are required to upgrade. this is where i came up my mind to make this at the first place. objective is to let user not to worry of forgot to run pip install causing project failed to run.

and your another question why not make it in batch but python.
indeed i myself make it up on batch at the first place for testing when the idea came up on my mind. but since i do not know much on docker yet if it can run batch or maybe it requires something else. so i just put it in as python since docker can run python for sure. anyone are welcome to make changes to improve it. haha

**Comment by aW3ikun** [comment]
> > I think running a bash script using python is not a good idea.
> > I refer to this https://stackoverflow.com/questions/69345839/how-to-run-a-pip-install-command-from-a-subproces-run.
> > > In general, though, I recommend avoiding reliance on a shell. That is, after all, why you are using Python and not, say, Bash.
> > 
> > 
> > Manually installing dependencies is more controllable than it.
> 
> Hi,
> 
> yup u r right, i agreed that installing dependencies manually is more better. but just realise that many of them are raising issues saying forgotten to run pip install whenever some dependencies are required to upgrade. this is where i came up my mind to make this at the first place. objective is to let user not to worry of forgot to run pip install causing project failed to run.
> 
> and your another question why not make it in batch but python. indeed i myself make it up on batch at the first place for testing when the idea came up on my mind. but since i do not know much on docker yet if it can run batch or maybe it requires something else. so i just put it in as python since docker can run python for sure. anyone are welcome to make changes to improve it. haha

For your first question, you could compare the local dependencies' versions with the version in `requirments.txt`. When they don't equal each other, use `logger.warning` or `logger.error` from `log.py` to notify users to upgrade their dependencies.  In my view, better than automatedly installing libraries. 
For example:
```
def check_verion() -> None:
    import pkg_resources
    import src.log

    # init loggger
    logger = src.log.setup_logger(__name__)

    # Read the requirements.txt file and add each line to a list
    with open('requirements.txt') as f:
        required = f.read().splitlines()


    # For each library listed in requirements.txt, check if the corresponding version is installed
    for package in required:
        # Use the pkg_resources library to get information about the installed version of the library
        package_name, package_verion = package.split('==')
        installed = pkg_resources.get_distribution(package_name)
        # Extract the library name and version number
        name, version = installed.project_name, installed.version
        # Compare the version number to see if it matches the one in requirements.txt
        if package != f'{name}=={version}':
            logger.warning(f'{name} version {version} is installed but does not match the requirements')
```

**Comment by jacky-chay** [comment]
@aW3ikun yes, it's a very nice piece of code haha have already replaced to my current one. Thank you

**Comment by Zero6992** [comment]
I think the issue of the desktop and server versions being out of sync has already been resolved in new version of chatGPT api, so I will check if we need two different requirements after the new version has been updated

**Comment by Zero6992** [comment]
> > > I think running a bash script using python is not a good idea.
> > > I refer to this https://stackoverflow.com/questions/69345839/how-to-run-a-pip-install-command-from-a-subproces-run.
> > > > In general, though, I recommend avoiding reliance on a shell. That is, after all, why you are using Python and not, say, Bash.
> > > 
> > > 
> > > Manually installing dependencies is more controllable than it.
> > 
> > 
> > Hi,
> > yup u r right, i agreed that installing dependencies manually is more better. but just realise that many of them are raising issues saying forgotten to run pip install whenever some dependencies are required to upgrade. this is where i came up my mind to make this at the first place. objective is to let user not to worry of forgot to run pip install causing project failed to run.
> > and your another question why not make it in batch but python. indeed i myself make it up on batch at the first place for testing when the idea came up on my mind. but since i do not know much on docker yet if it can run batch or maybe it requires something else. so i just put it in as python since docker can run python for sure. anyone are welcome to make changes to improve it. haha
> 
> For your first question, you could compare the local dependencies' versions with the version in `requirments.txt`. When they don't equal each other, use `logger.warning` or `logger.error` from `log.py` to notify users to upgrade their dependencies. In my view, better than automatedly installing libraries. For example:
> 
> ```python
> def check_verion() -> None:
>     import pkg_resources
>     import src.log
> 
>     # init loggger
>     logger = src.log.setup_logger(__name__)
> 
>     # Read the requirements.txt file and add each line to a list
>     with open('requirements.txt') as f:
>         required = f.read().splitlines()
> 
> 
>     # For each library listed in requirements.txt, check if the corresponding version is installed
>     for package in required:
>         # Use the pkg_resources library to get information about the installed version of the library
>         package_name, package_verion = package.split('==')
>         installed = pkg_resources.get_distribution(package_name)
>         # Extract the library name and version number
>         name, version = installed.project_name, installed.version
>         # Compare the version number to see if it matches the one in requirements.txt
>         if package != f'{name}=={version}':
>             logger.warning(f'{name} version {version} is installed but does not match the requirements')
> ```

This is a good way to remind they haven't updated to the latest version

Maybe you could rebase this part onto your other PR?

**Comment by jacky-chay** [comment]
> > yup sure will seperate this part out from here and delete the checking if docker thing.
> 
> Much appreciated

done

**Comment by Zero6992** [comment]
> > > yup sure will seperate this part out from here and delete the checking if docker thing.
> > 
> > 
> > Much appreciated
> 
> done

Only need changes to main.py, thanks

**Comment by jacky-chay** [comment]
> > > > yup sure will seperate this part out from here and delete the checking if docker thing.
> > > 
> > > 
> > > Much appreciated
> > 
> > 
> > done
> 
> Only need changes to `main.py`, thanks

alright, i have reverted the Dockerfile and removed the requirementsDocker.txt

**Comment by Zero6992** [comment]
> alright, i have reverted the Dockerfile and removed the requirementsDocker.txt

I have updated the requirements.txt, could you remove it as well? I'll merge then, thank you!

**Comment by jacky-chay** [comment]
> > alright, i have reverted the Dockerfile and removed the requirementsDocker.txt
> 
> I have updated `requirements.txt`, could you remove it as well? I'll merge then, thank you!

ok, updated requirements.txt same as your latest one.

**Pull request merged**
